version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: videos
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./videos.sql:/docker-entrypoint-initdb.d/videos.sql
